version: '3.8'

services:
  # ---------------------------------
  # Frontend Service (Next.js)
  # ---------------------------------
  frontend:
    image: yourdockerhubusername/my-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      # These URLs allow Next.js to communicate with the other containers
      # using their service names as hostnames. Docker's internal DNS handles this.
      - NEXT_PUBLIC_BACKEND_API_URL=http://backend:8000
      - NEXT_PUBLIC_AUTH_API_URL=http://auth_service:3001
    depends_on:
      - backend
      - auth_service

  # ---------------------------------
  # Backend Service (Python/FastAPI)
  # ---------------------------------
  backend:
    image: yourdockerhubusername/my-backend:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      # Injects secrets from the .env file in the same directory
      - ./.env

  # ---------------------------------
  # Auth Service (Node.js/Express)
  # ---------------------------------
  auth_service:
    image: yourdockerhubusername/my-auth-service:latest
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      # Injects secrets from the .env file in the same directory
      - ./.env